on:
  pull_request:
    types: [opened, edited]

jobs:
  test:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Test
        run: |
          kubectl cluster-info
